export const auraInterruptFlags = [
  {
    index: 0,
    flag: 1,
    name: "HITBYSPELL",
    comment: "",
  },
  {
    index: 1,
    flag: 2,
    name: "TAKE_DAMAGE",
    comment: "",
  },
  {
    index: 2,
    flag: 4,
    name: "CAST",
    comment: "",
  },
  {
    index: 3,
    flag: 8,
    name: "MOVE",
    comment: "",
  },
  {
    index: 4,
    flag: 16,
    name: "TURNING",
    comment: "",
  },
  {
    index: 5,
    flag: 32,
    name: "JUMP",
    comment: "",
  },
  {
    index: 6,
    flag: 64,
    name: "NOT_MOUNTED",
    comment: "",
  },
  {
    index: 7,
    flag: 128,
    name: "NOT_ABOVEWATER",
    comment: "",
  },
  {
    index: 8,
    flag: 256,
    name: "NOT_UNDERWATER",
    comment: "",
  },
  {
    index: 9,
    flag: 512,
    name: "NOT_SHEATHED",
    comment: "",
  },
  {
    index: 10,
    flag: 1024,
    name: "TALK",
    comment: "",
  },
  {
    index: 11,
    flag: 2048,
    name: "USE",
    comment: "",
  },
  {
    index: 12,
    flag: 4096,
    name: "MEELEE_ATTACK",
    comment: "",
  },
  {
    index: 13,
    flag: 8192,
    name: "SPELL_ATTACK",
    comment: "",
  },
  {
    index: 14,
    flag: 16384,
    name: "未知",
    comment: "",
  },
  {
    index: 15,
    flag: 32768,
    name: "TRANSFORM",
    comment: "",
  },
  {
    index: 16,
    flag: 65536,
    name: "未知",
    comment: "",
  },
  {
    index: 17,
    flag: 131072,
    name: "MOUNT",
    comment: "",
  },
  {
    index: 18,
    flag: 262144,
    name: "NOT_SEATED",
    comment: "",
  },
  {
    index: 19,
    flag: 524288,
    name: "CHANGE_MAP",
    comment: "",
  },
  {
    index: 20,
    flag: 1048576,
    name: "IMMUNE_OR_LOST_SELECTION",
    comment: "",
  },
  {
    index: 21,
    flag: 2097152,
    name: "未知",
    comment: "",
  },
  {
    index: 22,
    flag: 4194304,
    name: "TELEPORTED",
    comment: "",
  },
  {
    index: 23,
    flag: 8388608,
    name: "ENTER_PVP_COMBAT",
    comment: "",
  },
  {
    index: 24,
    flag: 16777216,
    name: "DIRECT_DAMAGE",
    comment: "",
  },
  {
    index: 25,
    flag: 33554432,
    name: "LANDING",
    comment: "",
  },
  {
    index: 26,
    flag: 67108864,
    name: "未知",
    comment: "",
  },
  {
    index: 27,
    flag: 134217728,
    name: "未知",
    comment: "",
  },
  {
    index: 28,
    flag: 268435456,
    name: "未知",
    comment: "",
  },
  {
    index: 29,
    flag: 536870912,
    name: "未知",
    comment: "",
  },
  {
    index: 30,
    flag: 1073741824,
    name: "未知",
    comment: "",
  },
  {
    index: 31,
    flag: 2147483648,
    name: "未知",
    comment: "",
  },
];