import { std } from "wow/wotlk";

const RASSN = std.CreatureTemplates.load(6771)
RASSN.Level.set(60, 60)
    .Stats.DamageMod.set(3)
    .Stats.HealthMod.set(3)
    .Rank.ELITE.set()

const LORD = std.CreatureTemplates.load(6768)
LORD.Level.set(61, 61)
    .Stats.DamageMod.set(5)
    .Stats.HealthMod.set(5)
    .Rank.ELITE.set()
    .AIName.AggressorAI()

const FAHRD = std.CreatureTemplates.load(6707)
FAHRD.Level.set(62, 62)
    .Stats.DamageMod.set(5)
    .Stats.HealthMod.set(5)
    .Rank.BOSS.set()
    .AIName.AggressorAI()

const WNSTNWOLF = std.CreatureTemplates.load(7323)
WNSTNWOLF.Level.set(60, 60)
    .Stats.DamageMod.set(3)
    .Stats.HealthMod.set(3)
    .Rank.ELITE.set()
    .AIName.AggressorAI()

const ZAN = std.CreatureTemplates.load(6777)
ZAN.Level.set(60, 60)
    .Stats.DamageMod.set(5)
    .Stats.HealthMod.set(5)
    .Rank.ELITE.set()
    .AIName.AggressorAI()

const SMDG = std.CreatureTemplates.load(6779)
SMDG.Level.set(60, 60)
    .Stats.DamageMod.set(5)
    .Stats.HealthMod.set(5)
    .Rank.ELITE.set()
    .AIName.AggressorAI()

const RGRD = std.CreatureTemplates.load(6766)
RGRD.Level.set(58, 58)