import { std } from "wow/wotlk";

const BXINGGLVE_R = std.Items.create("shrek6", "boxing-glove-right")
    .Name.enGB.set("Right Boxing Glove")
    .DisplayInfo.set(90000)
    .Quality.GREEN.set()
    .InventoryType.MAINHAND.set()
    .Class.FIST_WEAPON.set()
    .Durability.set(20)
    .Damage.addPhysical(10, 14)
    .Stats.addAgility(3)
    .Stats.addStrength(3)
    .Delay.set(2000)
    .Price.PlayerSellPrice.set(400)
    .ItemLevel.set(10)
    .RequiredLevel.set(10)
    .MaxStack.set(1)